#pragma once

#include <QMainWindow>
#include <QList>
#include <QString>
#include <QStringList>

#include <memory>

class QAction;
class QActionGroup;
class QCloseEvent;
class QDockWidget;
class QCheckBox;
class QLineEdit;
class QMenu;
class QPlainTextEdit;
class QPushButton;
class QListWidget;
class QStackedWidget;
class QTabWidget;
class QToolBar;
class QUndoStack;
class QTimer;
enum class FdsRunMode;
enum class SmokeviewLaunchMode;
enum class UiLanguage;
struct ApplicationSettings;

class SimulationTaskManager;
class SimulationTaskCenterWidget;
class FdsSceneSynchronizer;
struct FdsRunSummary;
struct FcProjectRuntimeSettings;
struct GeometryImportResult;
struct IfcImportResult;
class FcProject;
class FdsRecordEditor;
class MessageWidget;
class ModelTreeWidget;
class NativeResultViewerWidget;
class OccViewWidget;
class PropertiesWidget;
class ProjectRecoveryManager;
class QLabel;
class SnapManager;
class SmokeviewHostWidget;
class StartPageWidget;
class TutorialGuideWidget;

class MainWindow final : public QMainWindow
{
public:
    explicit MainWindow(QWidget* parent = nullptr);
    ~MainWindow() override;

    bool importIfcFile(const QString& filePath);
    bool importGeometryFile(const QString& filePath);
    bool importFdsInputFile(const QString& filePath);
    bool removeIfcObject(const QString& objectId, bool requestConfirmation = true);
    bool openResultFile(const QString& smvFilePath);
    bool reloadResultCase(const QString& objectId);
    bool closeResultCase(const QString& objectId);
    bool launchResultInSmokeview(const QString& objectId);
    bool openResultInNativeViewer(const QString& objectId);
    bool launchResultAnimation(const QString& objectId, SmokeviewLaunchMode mode);
    bool runFdsFile(const QString& inputFilePath,
                    FdsRunMode mode,
                    int processCount = 1,
                    int threadCount = 1);
    void loadSimpleTestBenchmark();
    void loadActivateVentsTutorial();
    void loadBucketTest2Tutorial();
    void loadCouchTutorial();
    void loadCouchSmoke12sTutorial();
    void loadHvacAircoilTutorial();
    void loadTunnelDemoTutorial();
    void loadTunnelSmoke10sTutorial();
    void startGuidedTutorial(const QString& tutorialId, bool restart = false);
    bool openProjectFile(const QString& filePath);
    bool saveProjectFile(const QString& filePath);
    bool exportCurrentProjectToFds(const QString& filePath);
    void setInterfaceLanguage(UiLanguage language);

protected:
    void closeEvent(QCloseEvent* event) override;

private:
    void createActions();
    void createMenus();
    void createToolBars();
    void createDockWidgets();
    void createCentralView();
    void createApplicationStatusBar();
    void connectActions();
    void createNewProject();
    void chooseAndOpenProject();
    void saveCurrentProject();
    void saveCurrentProjectAs();
    void showApplicationSettings();
    void showDiagnostics();
    void applyApplicationSettings(const ApplicationSettings& settings);
    void manageProjectResources();
    void packageCurrentProject();
    void unpackProjectPackage();
    void copyCurrentProjectToDirectory();
    void cleanUnusedResults();
    void showStartPage();
    void refreshStartPage();
    void chooseAndImportFds();
    void chooseAndExportFds();
    void editProjectSettings();
    void createFdsObject(const QString& initialKeyword = {});
    void editSelectedFdsObject();
    void editFdsObject(const QString& objectId);
    void validateCurrentProject();
    void createMeshesWithAssistant();
    void createFireSourceWithWizard();
    void createParticleSprayWithWizard();
    void createDeviceControlWithWizard();
    void createOutputWithWizard();
    void showControlLogicGraph();
    void showHvacNetworkGraph();
    void openPropertyLibrary();
    void manageScenarios();
    void runAllScenarios();
    void createTestBox();
    void createBuildingElement(int geometryKind);
    void startInteractiveWallDrawing();
    void finishInteractiveWallDrawing(double startX, double startY,
                                      double endX, double endY);
    void editSelectedBuildingGeometry();
    void editBuildingGeometry(const QString& objectId);
    void previewFdsBlocks();
    void convertBuildingGeometryToFds();
    void healSelectedGeometry();
    void performBooleanOperation(int operation);
    void importBackgroundImage();
    void selectAllModelObjects();
    void invertModelSelection();
    void selectObjectsByType();
    void selectObjectsByProperty();
    void selectObjectsByFloor();
    void transformSelectedGeometry();
    void commitManipulatorTransform(const QStringList& objectIds);
    void copyMoveSelectedGeometry();
    void arraySelectedGeometry();
    void measureSelectedGeometry();
    void mirrorSelectedGeometry();
    void alignSelectedGeometry();
    void copySelectedGeometryToFloor();
    void groupSelectedObjects();
    void createGeometryContainer(bool floor);
    void editFloorObject(const QString& objectId);
    void editSimulationParameters();
    void applyFloorViewState(const QString& floorObjectId);
    void hideSelectedObjects();
    void toggleSelectedObjectsLocked();
    void batchRenameSelectedObjects();
    void assignSurfacesToSelectedGeometry();
    void configureSnapping();
    void updateSnapStatus(const QString& detail = {});
    void updateMultiSelection(const QStringList& objectIds,
                              bool synchronizeTree,
                              bool synchronizeViewer);
    void importGeometry();
    bool commitGeometryImport(const GeometryImportResult& result);
    bool commitIfcImport(const IfcImportResult& result);
    void runCurrentProject();
    void runCurrentProjectWithInitialMode(FdsRunMode mode);
    void runCurrentProjectOpenMp();
    void runCurrentProjectParallel();
    void chooseAndRunFdsCase();
    void chooseAndRunFdsCaseParallel();
    void stopFdsCase();
    void handleFdsRunFinished(const FdsRunSummary& summary);
    void chooseAndOpenResults();
    void compareFdsResults();
    void reloadSelectedResults();
    void closeSelectedResults();
    void openSelectedInSmokeview();
    void openSelectedInNativeViewer();
    void openSelectedSmokeAnimation();
    void openSelectedSliceAnimation();
    void openSelectedParticleAnimation();
    void configureSmokeview();
    void retranslateUi();
    void refreshCurrentSelection();
    void deleteSelectedObject();
    void duplicateSelectedObject();
    void moveSelectedObjectUp();
    void moveSelectedObjectDown();
    bool duplicateObject(const QString& objectId);
    bool moveObject(const QString& objectId, int offset);
    bool removeObject(const QString& objectId, bool requestConfirmation = true);
    bool checkRemovalReferences(const QStringList& objectIds, bool requestConfirmation);
    int nextFdsSequenceIndex() const;
    void resetProjectRuntimeSettings();
    FcProjectRuntimeSettings currentRuntimeSettings() const;
    bool confirmProjectReplacement(const QString& operationDescription);
    void performAutoSave(const QString& reason);
    void offerRecoveryOnStartup();
    void clearCurrentRecovery();
    void addRecentProject(const QString& filePath);
    bool confirmTutorialReplacement();
    void rebuildFdsScene(bool fitAll = false,
                         const QString& selectedObjectId = {});
    void setObjectVisibility(const QString& objectId, bool visible);
    void isolateObject(const QString& objectId);
    void restoreModelVisibility();
    void viewNormalToObject(const QString& objectId);
    void updateWindowTitle();
    void resetDefaultLayout();
    void ensureFloatingFeedbackDockGeometry(QDockWidget* dock);
    void restoreSavedLayout();
    void saveCurrentLayout();
    void showModelWorkspace(int tabIndex = 0);
    void refreshRecordView();
    void saveAdvancedRecordDraft();
    void refreshTutorialContext();
    void highlightTutorialAction(const QString& actionObjectName,
                                 const QString& menuPath);

    QAction* m_newAction = nullptr;
    QAction* m_openAction = nullptr;
    QAction* m_saveAction = nullptr;
    QAction* m_saveAsAction = nullptr;
    QAction* m_importFdsAction = nullptr;
    QAction* m_exportFdsAction = nullptr;
    QAction* m_exitAction = nullptr;
    QAction* m_preferencesAction = nullptr;
    QAction* m_manageResourcesAction = nullptr;
    QAction* m_packageProjectAction = nullptr;
    QAction* m_unpackProjectAction = nullptr;
    QAction* m_copyProjectAction = nullptr;
    QAction* m_cleanResultsAction = nullptr;
    QAction* m_startPageAction = nullptr;

    QAction* m_undoAction = nullptr;
    QAction* m_redoAction = nullptr;
    QAction* m_deleteAction = nullptr;
    QAction* m_selectAllAction = nullptr;
    QAction* m_invertSelectionAction = nullptr;
    QAction* m_selectByTypeAction = nullptr;
    QAction* m_selectByPropertyAction = nullptr;
    QAction* m_selectByFloorAction = nullptr;
    QAction* m_transformAction = nullptr;
    QAction* m_transformGizmoAction = nullptr;
    QAction* m_copyMoveAction = nullptr;
    QAction* m_arrayAction = nullptr;
    QAction* m_measureAction = nullptr;
    QAction* m_mirrorAction = nullptr;
    QAction* m_alignAction = nullptr;
    QAction* m_copyToFloorAction = nullptr;
    QAction* m_groupAction = nullptr;
    QAction* m_createFolderAction = nullptr;
    QAction* m_createFloorAction = nullptr;
    QAction* m_hideSelectedAction = nullptr;
    QAction* m_lockSelectedAction = nullptr;
    QAction* m_batchRenameAction = nullptr;
    QAction* m_assignSurfacesAction = nullptr;
    QAction* m_snapEnabledAction = nullptr;
    QAction* m_snapSettingsAction = nullptr;
    QAction* m_editObjectAction = nullptr;
    QAction* m_duplicateAction = nullptr;
    QAction* m_moveUpAction = nullptr;
    QAction* m_moveDownAction = nullptr;

    QAction* m_selectAction = nullptr;
    QAction* m_fitAllAction = nullptr;
    QAction* m_restoreVisibilityAction = nullptr;
    QAction* m_fitSelectionAction = nullptr;
    QAction* m_perspectiveAction = nullptr;
    QAction* m_orthographicAction = nullptr;
    QAction* m_saveViewAction = nullptr;
    QAction* m_restoreViewAction = nullptr;
    QAction* m_rotationCenterAction = nullptr;
    QAction* m_axesAction = nullptr;
    QAction* m_backgroundAction = nullptr;
    QAction* m_clippingPlaneAction = nullptr;
    QAction* m_frontAction = nullptr;
    QAction* m_backAction = nullptr;
    QAction* m_leftAction = nullptr;
    QAction* m_rightAction = nullptr;
    QAction* m_topAction = nullptr;
    QAction* m_bottomAction = nullptr;
    QAction* m_isometricAction = nullptr;
    QAction* m_resetLayoutAction = nullptr;

    QAction* m_createBoxAction = nullptr;
    QAction* m_createWallAction = nullptr;
    QAction* m_drawWallAction = nullptr;
    QAction* m_createRoomAction = nullptr;
    QList<QAction*> m_buildingGeometryActions;
    QAction* m_previewFdsBlocksAction = nullptr;
    QAction* m_convertGeometryToFdsAction = nullptr;
    QAction* m_healGeometryAction = nullptr;
    QAction* m_unionGeometryAction = nullptr;
    QAction* m_cutGeometryAction = nullptr;
    QAction* m_intersectGeometryAction = nullptr;
    QAction* m_splitGeometryAction = nullptr;
    QAction* m_backgroundImageAction = nullptr;
    QAction* m_importGeometryAction = nullptr;

    QAction* m_meshAction = nullptr;
    QAction* m_speciesAction = nullptr;
    QAction* m_materialAction = nullptr;
    QAction* m_surfaceAction = nullptr;
    QAction* m_reactionAction = nullptr;
    QAction* m_particleAction = nullptr;
    QAction* m_ventAction = nullptr;
    QAction* m_deviceAction = nullptr;
    QAction* m_controlAction = nullptr;
    QAction* m_hvacAction = nullptr;
    QAction* m_initialConditionAction = nullptr;
    QAction* m_outputAction = nullptr;
    QAction* m_addFdsObjectAction = nullptr;
    QAction* m_meshEngineeringAction = nullptr;
    QAction* m_fireSourceWizardAction = nullptr;
    QAction* m_particleSprayWizardAction = nullptr;
    QAction* m_deviceControlWizardAction = nullptr;
    QAction* m_outputWizardAction = nullptr;
    QAction* m_controlGraphAction = nullptr;
    QAction* m_hvacGraphAction = nullptr;
    QAction* m_propertyLibraryAction = nullptr;
    QAction* m_scenarioManagerAction = nullptr;
    QAction* m_runAllScenariosAction = nullptr;
    QAction* m_projectSettingsAction = nullptr;
    QAction* m_simulationParametersAction = nullptr;
    QAction* m_simpleTestAction = nullptr;
    QAction* m_activateVentsAction = nullptr;
    QAction* m_bucketTest2Action = nullptr;
    QAction* m_couchAction = nullptr;
    QAction* m_couchSmoke12sAction = nullptr;
    QAction* m_hvacAircoilAction = nullptr;
    QAction* m_tunnelDemoAction = nullptr;
    QAction* m_tunnelSmoke10sAction = nullptr;
    QList<QAction*> m_guidedTutorialActions;

    QAction* m_runAction = nullptr;
    QAction* m_runParallelAction = nullptr;
    QAction* m_runOpenMpAction = nullptr;
    QAction* m_stopAction = nullptr;
    QAction* m_validateAction = nullptr;

    QAction* m_openResultsAction = nullptr;
    QAction* m_compareResultsAction = nullptr;
    QAction* m_reloadResultsAction = nullptr;
    QAction* m_closeResultsAction = nullptr;
    QAction* m_openSmokeviewAction = nullptr;
    QAction* m_openNativeResultsAction = nullptr;
    QAction* m_openSmokeAnimationAction = nullptr;
    QAction* m_openSliceAnimationAction = nullptr;
    QAction* m_openParticleAnimationAction = nullptr;
    QAction* m_configureSmokeviewAction = nullptr;
    QAction* m_englishAction = nullptr;
    QAction* m_chineseAction = nullptr;
    QActionGroup* m_languageActionGroup = nullptr;
    QAction* m_aboutAction = nullptr;
    QAction* m_diagnosticsAction = nullptr;

    QMenu* m_fileMenu = nullptr;
    QMenu* m_editMenu = nullptr;
    QMenu* m_viewMenu = nullptr;
    QMenu* m_geometryMenu = nullptr;
    QMenu* m_buildingElementsMenu = nullptr;
    QMenu* m_profileGeometryMenu = nullptr;
    QMenu* m_openingsMenu = nullptr;
    QMenu* m_geometryOperationsMenu = nullptr;
    QMenu* m_modelMenu = nullptr;
    QMenu* m_modelAssistantsMenu = nullptr;
    QMenu* m_tutorialMenu = nullptr;
    QMenu* m_tutorialExamplesMenu = nullptr;
    QMenu* m_simulationMenu = nullptr;
    QMenu* m_resultsMenu = nullptr;
    QMenu* m_languageMenu = nullptr;
    QMenu* m_helpMenu = nullptr;
    QToolBar* m_mainToolBar = nullptr;
    QStackedWidget* m_centralStack = nullptr;
    QTabWidget* m_workspaceTabs = nullptr;

    QDockWidget* m_modelTreeDock = nullptr;
    QDockWidget* m_propertiesDock = nullptr;
    QDockWidget* m_messagesDock = nullptr;
    QDockWidget* m_taskCenterDock = nullptr;
    QDockWidget* m_inspectorDock = nullptr;
    QDockWidget* m_fdsOutputDock = nullptr;
    QDockWidget* m_resultStatusDock = nullptr;
    QDockWidget* m_tutorialGuideDock = nullptr;

    ModelTreeWidget* m_modelTreeWidget = nullptr;
    PropertiesWidget* m_propertiesWidget = nullptr;
    MessageWidget* m_messageWidget = nullptr;
    SimulationTaskCenterWidget* m_taskCenterWidget = nullptr;
    QTabWidget* m_inspectorTabs = nullptr;
    QLabel* m_activeToolLabel = nullptr;
    QListWidget* m_selectionList = nullptr;
    QListWidget* m_validationList = nullptr;
    QPlainTextEdit* m_fdsOutputLog = nullptr;
    QLabel* m_resultStatusLabel = nullptr;
    OccViewWidget* m_occViewWidget = nullptr;
    OccViewWidget* m_planViewWidget = nullptr;
    OccViewWidget* m_wallSketchView = nullptr;
    FdsRecordEditor* m_recordView = nullptr;
    QLineEdit* m_recordSearchEdit = nullptr;
    QCheckBox* m_recordAdvancedMode = nullptr;
    QPushButton* m_recordApplyButton = nullptr;
    NativeResultViewerWidget* m_nativeResultViewerWidget = nullptr;
    SmokeviewHostWidget* m_smokeviewHostWidget = nullptr;
    StartPageWidget* m_startPageWidget = nullptr;
    TutorialGuideWidget* m_tutorialGuideWidget = nullptr;
    SimulationTaskManager* m_taskManager = nullptr;
    std::unique_ptr<FdsSceneSynchronizer> m_fdsSceneSynchronizer;
    std::unique_ptr<FdsSceneSynchronizer> m_planSceneSynchronizer;
    std::unique_ptr<SnapManager> m_snapManager;
    std::unique_ptr<ProjectRecoveryManager> m_recoveryManager;
    QTimer* m_autoSaveTimer = nullptr;
    QLabel* m_snapStatusLabel = nullptr;

    std::unique_ptr<FcProject> m_project;
    QString m_currentProjectPath;
    QString m_currentFdsPath;
    QString m_projectResultDirectory;
    QString m_projectSolverExecutable;
    QString m_lastRecoverySnapshotPath;
    int m_projectParallelProcessCount = 1;
    int m_nextBoxNumber = 1;
    int m_nextGroupNumber = 1;
    QStringList m_fdsPreviewObjectIds;
    QString m_wallSketchName;
    double m_wallSketchElevation = 0.0;
    double m_wallSketchThickness = 0.2;
    double m_wallSketchHeight = 3.0;
    int m_wallSketchBaseline = 1;
    bool m_wallSketchContinuous = false;
    bool m_wallSketchAutoConnect = true;
    int m_wallSketchSegmentNumber = 0;
    QString m_wallSketchFloorId;
    QString m_activeFloorId;
    QUndoStack* m_undoStack = nullptr;
    bool m_isolationActive = false;
    unsigned int m_layoutRevision = 0;
};
